# Generated by Django 5.1.3 on 2024-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('position', models.IntegerField(help_text='Position of the menu item')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
