# Generated by Django 5.1.3 on 2026-01-22 10:57

import django.db.models.deletion
import django_ckeditor_5.fields
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Author Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Default_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('news_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Default_pages',
            },
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('english_title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(max_length=100)),
                ('position', models.IntegerField(help_text='Position of the menu item')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter the robots.txt content. Use User-agent, Disallow, Allow, and Sitemap directives.')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, a default robots.txt will be served instead.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'verbose_name_plural': 'Robots.txt',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Home page meta title', max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Home page meta description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNewTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='URLRedirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(help_text='Old URL path (e.g., /old-page/)', max_length=500, unique=True)),
                ('new_url', models.CharField(help_text='New URL path or full URL (e.g., /new-page/ or https://example.com)', max_length=500)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', help_text='HTTP redirect status code', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this redirection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'URL Redirection',
                'verbose_name_plural': 'URL Redirections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower number = higher position (Senior = 1, Junior = 2)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='home.authorcategory')),
            ],
            options={
                'ordering': ['priority', 'title'],
                'unique_together': {('category', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='authors/')),
                ('description', models.TextField()),
                ('position', models.PositiveIntegerField(default=0, help_text='Position for ordering (lower number appears first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='home.authorcategory')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='home.authorrole')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_sub_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('sub_content', models.TextField(blank=True, max_length=1000, null=True)),
                ('news_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('heading_image', models.ImageField(upload_to='news/', validators=[home.models.validate_image])),
                ('heading_image_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='news/', validators=[home.models.validate_image])),
                ('main_image_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload a PDF file to attach to this news article', null=True, upload_to='news_pdfs/')),
                ('pdf_title', models.CharField(blank=True, help_text='Optional title/description for the PDF', max_length=200, null=True)),
                ('reporter', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, help_text='Schedule this news to be published at a specific date and time', null=True)),
                ('category', models.ManyToManyField(blank=True, to='home.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.navbaritem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('love', '❤️ Love'), ('clap', '👏 Clap'), ('smile', '🙂 Smile'), ('sad', '😞 Sad')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='home.news')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True)),
                ('news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.news')),
            ],
            options={
                'verbose_name': 'News SEO',
                'verbose_name_plural': 'News SEO',
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='home.news')),
            ],
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.default_pages')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.news')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True)),
                ('section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.navbaritem')),
            ],
            options={
                'verbose_name': 'Section SEO',
                'verbose_name_plural': 'Section SEO',
            },
        ),
        migrations.CreateModel(
            name='SpecialNewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_news', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.news')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('special_news_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.specialnewtitle')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('english_title', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(help_text='Position of the sub section')),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.navbaritem')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subsection'),
        ),
        migrations.CreateModel(
            name='SubSectionSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True)),
                ('subsection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.subsection')),
            ],
            options={
                'verbose_name': 'SubSection SEO',
                'verbose_name_plural': 'SubSection SEO',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='home.tag'),
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('youtube_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.navbaritem')),
            ],
        ),
    ]
