# Generated by Django 5.1.3 on 2026-01-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title for admin reference', max_length=200)),
                ('image', models.ImageField(help_text='Upload banner image', upload_to='banners/')),
                ('position', models.IntegerField(default=0, help_text='Order of banner (lower number appears first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(help_text='Section to redirect when banner is clicked', on_delete=django.db.models.deletion.CASCADE, to='home.navbaritem')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
