# Generated by Django 5.1.3 on 2024-11-13 17:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('heading_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('image_title', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('news_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.navbaritem')),
            ],
        ),
    ]
