# Generated by Django 5.1.3 on 2026-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionScoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='নির্বাচনী স্কোরবোর্ড', help_text='Scoreboard title', max_length=200)),
                ('party1_name', models.CharField(default='বিএনপি জোট', help_text='Party 1 name', max_length=100)),
                ('party1_logo', models.ImageField(blank=True, help_text='Party 1 logo', null=True, upload_to='election/')),
                ('party1_score', models.IntegerField(default=0, help_text='Party 1 score/seats')),
                ('party2_name', models.CharField(default='জামায়াত জোট', help_text='Party 2 name', max_length=100)),
                ('party2_logo', models.ImageField(blank=True, help_text='Party 2 logo', null=True, upload_to='election/')),
                ('party2_score', models.IntegerField(default=0, help_text='Party 2 score/seats')),
                ('is_live', models.BooleanField(default=True, help_text='Show LIVE indicator')),
                ('is_active', models.BooleanField(default=True, help_text='Show scoreboard on homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Election Scoreboard',
                'verbose_name_plural': 'Election Scoreboards',
                'ordering': ['-created_at'],
            },
        ),
    ]
