# Generated by Django 5.1.3 on 2026-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_electionscoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionscoreboard',
            name='others_logo',
            field=models.ImageField(blank=True, help_text='Others logo', null=True, upload_to='election/'),
        ),
        migrations.AddField(
            model_name='electionscoreboard',
            name='others_name',
            field=models.CharField(default='অন্যান্য', help_text='Others name', max_length=100),
        ),
        migrations.AddField(
            model_name='electionscoreboard',
            name='others_score',
            field=models.IntegerField(default=0, help_text='Others score/seats'),
        ),
    ]
