# Generated by Django 5.1.3 on 2024-11-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sub_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
