# Generated by Django 5.1.3 on 2024-11-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_news_sub_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='news', to='home.category'),
        ),
    ]
