# Generated by Django 5.1.3 on 2026-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_electionscoreboard_others_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionscoreboard',
            name='others_logo',
        ),
        migrations.RemoveField(
            model_name='electionscoreboard',
            name='others_name',
        ),
        migrations.RemoveField(
            model_name='electionscoreboard',
            name='others_score',
        ),
        migrations.AddField(
            model_name='electionscoreboard',
            name='party3_logo',
            field=models.ImageField(blank=True, help_text='Party 3 logo', null=True, upload_to='election/'),
        ),
        migrations.AddField(
            model_name='electionscoreboard',
            name='party3_name',
            field=models.CharField(default='অন্যান্য', help_text='Party 3 name', max_length=100),
        ),
        migrations.AddField(
            model_name='electionscoreboard',
            name='party3_score',
            field=models.IntegerField(default=0, help_text='Party 3 score/seats'),
        ),
    ]
