# Generated by Django 5.1.3 on 2026-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_electionscoreboard_others_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionLiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='ঢাকা', max_length=80)),
                ('bnp', models.PositiveIntegerField(default=0)),
                ('jamaat', models.PositiveIntegerField(default=0)),
                ('others', models.PositiveIntegerField(default=0)),
                ('ticker', models.TextField(default='সর্বশেষ আপডেট: ভোট গণনা চলছে • কেন্দ্র থেকে কেন্দ্রভিত্তিক ফল আসতে শুরু করেছে • লাইভ স্কোরবোর্ড আপডেট হচ্ছে •')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
