# Generated by Django 5.1.3 on 2026-02-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_electionlivescore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionlivescore',
            options={'verbose_name': 'Election Live Score', 'verbose_name_plural': 'Election Live Scores'},
        ),
    ]
