# Generated by Django 5.1.3 on 2024-11-26 20:17

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_news_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, to='home.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='heading_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', validators=[home.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', validators=[home.models.validate_image]),
        ),
    ]
