# Generated by Django 5.1.3 on 2026-02-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_electionlivescore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionlivescore',
            name='bnp_logo',
            field=models.FileField(blank=True, null=True, upload_to='election_logos/'),
        ),
        migrations.AddField(
            model_name='electionlivescore',
            name='jamaat_logo',
            field=models.FileField(blank=True, null=True, upload_to='election_logos/'),
        ),
        migrations.AddField(
            model_name='electionlivescore',
            name='others_logo',
            field=models.FileField(blank=True, null=True, upload_to='election_logos/'),
        ),
    ]
