# Generated by Django 5.1.3 on 2026-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_electionlivescore_bnp_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionlivescore',
            name='channel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='scoreboard/'),
        ),
    ]
