# Generated by Django 5.1.3 on 2025-01-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_news_created_by_news_updated_at_news_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image_title',
            new_name='heading_image_title',
        ),
        migrations.AddField(
            model_name='news',
            name='main_image_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='top_sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
