# Generated by Django 5.1.3 on 2025-01-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_image_title_news_heading_image_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_pages',
            name='image',
        ),
    ]
