# Generated by Django 5.1.3 on 2025-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reporter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
