# Generated by Django 5.1.3 on 2025-07-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_specialnewtitle_remove_news_reporter_newsreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reporter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
