# Generated by Django 5.1.3 on 2025-07-29 13:48

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_news_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='heading_image',
            field=models.ImageField(default=1, upload_to='news/', validators=[home.models.validate_image]),
            preserve_default=False,
        ),
    ]
