# Generated by Django 5.1.3 on 2025-09-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_news_heading_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialnewsection',
            name='impact_and_reaction',
        ),
        migrations.RemoveField(
            model_name='specialnewsection',
            name='last_update',
        ),
    ]
