# Generated by Django 5.1.3 on 2025-12-05 15:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_news_heading_image_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
