# Generated by Django 5.1.3 on 2025-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_news_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule this news to be published at a specific date and time', null=True),
        ),
    ]
