# Generated by Django 5.1.3 on 2025-12-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_add_videopost_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLRedirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(help_text='Old URL path (e.g., /old-page/)', max_length=500, unique=True)),
                ('new_url', models.CharField(help_text='New URL path or full URL (e.g., /new-page/ or https://example.com)', max_length=500)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', help_text='HTTP redirect status code', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this redirection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'URL Redirection',
                'verbose_name_plural': 'URL Redirections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.news')),
            ],
            options={
                'verbose_name': 'News SEO',
                'verbose_name_plural': 'News SEO',
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.default_pages')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
    ]
