# Generated by Django 5.1.3 on 2025-12-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_urlredirection_newsseo_pageseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsseo',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True),
        ),
    ]
