# Generated by Django 5.1.3 on 2025-12-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_newsseo_canonical_url_pageseo_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='english_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='english_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
