# Generated by Django 5.1.3 on 2026-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_authorcategory_authorrole_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorrole',
            options={'ordering': ['priority', 'title']},
        ),
        migrations.AddField(
            model_name='authorrole',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Lower number = higher position (Senior = 1, Junior = 2)'),
        ),
    ]
