# Generated by Django 5.1.3 on 2026-01-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_tag_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True)),
                ('section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.navbaritem')),
            ],
            options={
                'verbose_name': 'Section SEO',
                'verbose_name_plural': 'Section SEO',
            },
        ),
        migrations.CreateModel(
            name='SubSectionSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title (recommended: 50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (recommended: 150-160 characters)', max_length=160, null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author name for meta tag', max_length=100, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta title)', max_length=100, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=200, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px, leave blank to use default)', null=True, upload_to='og_images/')),
                ('og_type', models.CharField(default='article', help_text='Open Graph type (article, website, etc.)', max_length=50)),
                ('og_site_name', models.CharField(blank=True, help_text='Site name for Open Graph', max_length=100, null=True)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (leave blank to use meta title)', max_length=100, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description (leave blank to use meta description)', max_length=200, null=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (leave blank to use og_image)', null=True, upload_to='twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL - The preferred URL for this page (leave blank to use current URL). Helps prevent duplicate content issues.', max_length=500, null=True)),
                ('subsection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='home.subsection')),
            ],
            options={
                'verbose_name': 'SubSection SEO',
                'verbose_name_plural': 'SubSection SEO',
            },
        ),
    ]
