# Generated by Django 5.1.3 on 2026-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_sectionseo_subsectionseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter the robots.txt content. Use User-agent, Disallow, Allow, and Sitemap directives.')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, a default robots.txt will be served instead.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'verbose_name_plural': 'Robots.txt',
                'ordering': ['-updated_at'],
            },
        ),
    ]
