# Generated by Django 5.2.5 on 2026-01-18 06:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_robotstxt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_pages',
            name='news_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
