# Generated by Django 5.1.3 on 2026-01-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_robotstxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_pages',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
