# Generated by Django 5.1.3 on 2026-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_default_pages_news_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_pages',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
