# Generated by Django 5.2.5 on 2026-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_default_pages_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Home page meta description', null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Home page meta title', max_length=200, null=True),
        ),
    ]
