# Generated by Django 5.1.3 on 2026-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_siteinfo_meta_description_siteinfo_meta_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='author',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position for ordering (lower number appears first)'),
        ),
    ]
