# Generated by Django 5.1.3 on 2026-01-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_author_options_author_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload a PDF file to attach to this news article', null=True, upload_to='news_pdfs/'),
        ),
        migrations.AddField(
            model_name='news',
            name='pdf_title',
            field=models.CharField(blank=True, help_text='Optional title/description for the PDF', max_length=200, null=True),
        ),
    ]
